cc_library(
    name = "circles",
    srcs = ["circles.cc"],
    hdrs = ["circles.h"],
)

cc_test(
    name = "circles_test",
    srcs = ["circles_test.cc"],
    deps = [
        ":circles",
        "@catch2//:catch2_main",
    ],
)
