cc_library(
    name = "point",
    srcs = ["point.cc"],
    hdrs = ["point.h"],
)

cc_test(
    name = "point_test",
    srcs = ["point_test.cc"],
    deps = [
        ":point",
        "@catch2//:catch2_main",
    ],
)
